version: "3.11"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile의 이름이 다르거나 위치가 다른 경우에 명시적으로 지정
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: flake8
    environment:
      - DB_HOST=db
      - DB_NAME=miniproject
      - DB_USER=glory
      - DB_PASS=1234
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=miniproject
      - POSTGRES_USER=glory
      - POSTGRES_PASSWORD=1234
