# version: "3.11"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=miniproject
      - DB_USER=glory
      - DB_PASS=1234
    depends_on:
      - db


  db:
    image: postgres:16-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=miniproject
      - POSTGRES_USER=glory
      - POSTGRES_PASSWORD=1234