name: Checks

on: [push]

jobs:
  test-lint:
    name: Mini Project Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MINI_GLORY_NAME }}
          password: ${{ secrets.MINI_GLORY_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        working-directory: scraping_project/ozscraping-glory  # 작업 디렉토리를 올바르게 설정
        run: |
          docker-compose run --rm app sh -c "flake8"
