
  name: Checks 
  
  on: [push] 
  
  jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04 
      steps: 

        - name: Login in to Docker Hub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.MINI_GLORY_NAME }}
            password: ${{ secrets.MINI_GLORY_TOKEN }}
  
        - name: Checkout 
          uses: actions/checkout@v2
        
        - name: Lint 
          run: docker-compose run --rm app sh -c "flake8"